### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#10]
You can currently initiate combat, but it will crash the engine.

**Comment by gatperdut** [comment]
The weapon and critical tables are huge, so I cannot afford to to load them into the db everytime I need to drop it. For the time being, I can prevent combat from starting. Planning to add an arena soonish so it can be tested out.

**Comment by chatomud** [comment]
basics are done. criticals are missing (as well as some polishing in the messages which it no doubt needs) but we can take care of those in a different ticket. closing.
