### ISSUE TITLE
Add Staff Commands

### ISSUE THREAD

**Issue by TulkasAM** [chatomud/chatomud#24]
Basic stuff for admins on the mud, like:

* ~~'Echoes'~~
* ~~'Pechoes' (directed at individual players)~~
* ~~'Go' (?) command (ie teleport to rnum blah)~~
* ~~Teleporting PCs/NPCs around~~
* Stuff for loading NPCs, items, NPCs with items
* ~~Stopping all combat in a room~~
* ~~Going invis/wizinvis~~
* Wiznet or admin chat commands for sending messages between admins
* Petition responses
* ~~Snoop (see what a player/NPC sees and all their inputs)~~
* ~~'As' command (very useful conduit command when controlling multiple NPCs, ie 'as orc yell I will kill you!') - Note it's also very useful for 'as Shianek <command>', so you can even stat, score or look to see what's up~~
* ~~'Assume' command, I think it was called something else in SoI, but being able to 'enter' bodies of NPCs directly so that all your inputs become theirs~~

I'm sure there is a lot more. Feel free to add.

**Comment by chatomud** [comment]
assume is implemented as 'possess/release'. the rest will be done!

**Comment by chatomud** [comment]
there are a lot of corner cases for invisibility. I would appreciate if you could test it a bit @TulkasAM @chrimcco @Ancalagon071 particularly that there are no stray messages (like `someone does something` when there really shouldn't be an echo) in:
* following (either direct, or falling in line with someone's leader)
* stop following
* people following you and becoming invisible.
* being the leader of a group and following someone else while invisible.
* retreating (either triggered personally or triggered by the group leader)
* anything else you can think of.

**Comment by chatomud** [comment]
teleporting oneself:
`go <room_id>`
teleporting someone:
`teleport <keyword> <room_id>`

both commands work in the same philosophy:
* if leading a group, you will be asked for confirmation by appending a `!`. This will move all the group.
* if following a group, confirmation is needed too. This will remove the pc from the group.

Also, room IDs are displayed next to the room title. Or you can just check it in the web.
