### ISSUE TITLE
adding lists to commands like spawn

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#25]
when you type spawn blank, you get the infamous 'huh?'

it'd be a feature to have a list of available 'spawns' come up when the command is entered without a qualifier. 

'spawn mob' could bring up a list of available mobs

'spawn object' could bring up a list of available objects

feasible?

**Comment by chatomud** [comment]
You have a list of all possible items to spawn in the portal under Item Templates. Same will be done for npcs and outfitters. will that do? I'd like to keep command line stuff to a minimun

**Comment by chatomud** [comment]
take a look i  the weekend once I deploy yhe combat. Spawning an item will be done through the portal with a form
