### ISSUE TITLE
switching opponents in combat

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#37]
a long-eared, cross-eyed goblin misses you, you are too fast.

<******# |||||>144/144[a long-eared, cross-eyed goblin <   ***>]
hit 2.gob
You shift your attention to a flat-eared, long-eared goblin.
<******# |||||>144/144[a long-eared, cross-eyed goblin <   ***>]

a flat-eared, long-eared goblin misses you with a good, weapon_low_carbon_steel dagger, you are too fast.

<******# |||||>144/144[a flat-eared, long-eared goblin <******>]
A glow illuminates the eastern horizon.
<******# |||||>144/144[a flat-eared, long-eared goblin <******>]
%%% Disconnected from server.

**Comment by chatomud** [comment]
should be fixed now. reopen if happens again?
