### ISSUE TITLE
Wearing items junks them

### ISSUE THREAD

**Issue by TulkasAM** [chatomud/chatomud#38]
<  ****# |||||>57/90
get qui
You take a leather quiver.
<  ****# |||||>57/90
wear qui
You wear a leather quiver on your left shoulder.
<  ****# |||||>57/90
get arrow
You take an iron-tipped arrow.
<  ****# |||||>57/90
put arrow qui
You cannot find the 'qui'.
<  ****# |||||>57/90
inv
you are carrying:
<wielded in right hand> - a outstanding weapon_ash crossbow
<held in your left hand> - an iron-tipped arrow

<on your head> - a artifact, armor_mithril spangen-helm
<around your torso> - a shirt of iron chainmail
<on your left shoulder> - a deer-leather harness
<around your right wrist> - a warg-leather strap
<on your legs> - a pair of tanned-leather leggings

Where did they go? No one knows.

**Comment by chatomud** [comment]
fixed
