### ISSUE TITLE
multiple combatants - one dies

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#39]
I have a feeling that if you're fighting multiple combatants, and one dies, it may cause a crash.

a flat-eared, mossy-green skinned goblin misses you with a outstanding, weapon_low_carbon_steel dagger, you dodge it.
AL1/ARM0: Roll is 30 = (53 UR + 32 AM - 55D + 0 ARM, 89 MMS). 

<******# |||||>88/88[a flat-eared, long-eared goblin <     *>]

a flat-eared, long-eared goblin misses you with a artifact, weapon_wrought_iron dagger, you dodge it. AL1/ARM0: Roll is 7
= (19 UR + 50 AM - 62D + 0 ARM, 89 MMS). 

<******# |||||>88/88[a flat-eared, long-eared goblin <     *>]

You strike a flat-eared, long-eared goblin in the right shin. AL6/ARM5: Roll is 54 = (29 UR + 38 AM - 18D + 5 ARM, 39
MMS). 3 hits. Not a critical.

<******# |||||>88/88[a flat-eared, long-eared goblin <     *>]
%%% Disconnected from server.

**Comment by chatomud** [comment]
I have found a pretty big and obvious problem which I think is what caused your crash. However, there was a problem with the logs (I hadn't realized until now that they are in-memory, so logs before the current reboot were not stored) so I cannot confirm. Let me know if it happens again?
