### ISSUE TITLE
For Building Tools

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#8]
Had an idea after playing around with the web portal building tools.

Can we group rooms together in zones somehow, and have them sorted on the web portal for building purposes?

backburner item to be considered when tweaking building tools.

**Comment by gatperdut** [comment]
We will do this. 3 groups:
Super area: encompasses areas. Example: city, forest.
Area: encompasses rooms. Example: city streets, shop backroom.
Room: just a regular room.

Echoes can be cast at all 3 levels, and they will bleed to any lower level. Echoing in a super area will cast the echo to every single room in the area (e.g. mustering), echoing in an area will affect just the rooms in that area (ringing a bell in a shop, e.g.)

**Comment by chrimcco** [comment]
that is ideal. love it.

**Comment by chatomud** [comment]
done!
