### ISSUE TITLE
Text Colours - ANSI

### ISSUE THREAD

**Issue by chrimcco** [chatomud/chatomud#9]
traditional diku ansi colours for mobiles (purple) and objects (green).

**Comment by gatperdut** [comment]
Isn't that already there from the beginning? Do you have ansi coloring on? You can toggle it on the main menu, after logging in.
Also, what color should objects be when they are listed as contents of a room? Full description in green?

**Comment by chrimcco** [comment]
it was the gmud client. on blowtorch (android app) and mudlet, it works fine.

closed!
